import { db } from '../../lib/firebase';
import {
    collection,
    getDocs,
    doc,
    addDoc,
    updateDoc,
    deleteDoc,
    onSnapshot,
    QuerySnapshot,
    query,
    orderBy,
    setDoc
} from 'firebase/firestore';
import { Supplier, PurchaseOrder, POStatus } from '../../types/procurement';

const SUPPLIER_COLLECTION = 'suppliers';
const PO_COLLECTION = 'purchase_orders';

class ProcurementServiceFirebase {

    // --- SUPPLIERS ---

    async getSuppliers(): Promise<Supplier[]> {
        const q = query(collection(db, SUPPLIER_COLLECTION));
        const querySnapshot = await getDocs(q);
        return querySnapshot.docs.map(doc => ({
            id: doc.id,
            ...doc.data()
        } as Supplier));
    }

    async addSupplier(data: Omit<Supplier, 'id'>): Promise<Supplier> {
        const docRef = await addDoc(collection(db, SUPPLIER_COLLECTION), data);
        return { id: docRef.id, ...data };
    }

    async deleteSupplier(id: string): Promise<void> {
        await deleteDoc(doc(db, SUPPLIER_COLLECTION, id));
    }

    subscribeSuppliers(callback: (suppliers: Supplier[]) => void): () => void {
        const q = query(collection(db, SUPPLIER_COLLECTION));
        return onSnapshot(q, (snapshot: QuerySnapshot) => {
            const items = snapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data()
            } as Supplier));
            callback(items);
        });
    }

    // --- PURCHASE ORDERS ---

    async getPOs(): Promise<PurchaseOrder[]> {
        const q = query(collection(db, PO_COLLECTION), orderBy('date', 'desc'));
        const querySnapshot = await getDocs(q);
        return querySnapshot.docs.map(doc => ({
            id: doc.id,
            ...doc.data()
        } as PurchaseOrder));
    }

    async createPO(data: PurchaseOrder): Promise<void> {
        // PO usually has specific ID format if generated by system, or valid Firestore ID.
        // Context generates 'po-timestamp'. Let's try to keep using that if passed, or allow auto-gen.
        // If the ID is passed in data, use setDoc.

        const { id, ...rest } = data;
        if (id) {
            await setDoc(doc(db, PO_COLLECTION, id), rest);
        } else {
            await addDoc(collection(db, PO_COLLECTION), rest);
        }
    }

    async updatePOStatus(id: string, status: POStatus): Promise<void> {
        const docRef = doc(db, PO_COLLECTION, id);
        await updateDoc(docRef, { status });
    }

    subscribePOs(callback: (pos: PurchaseOrder[]) => void): () => void {
        const q = query(collection(db, PO_COLLECTION), orderBy('date', 'desc'));
        return onSnapshot(q, (snapshot: QuerySnapshot) => {
            const items = snapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data()
            } as PurchaseOrder));
            callback(items);
        });
    }

    // --- SEEDING ---
    async seedInitialSuppliers(suppliers: Omit<Supplier, 'id'>[]): Promise<void> {
        const existing = await this.getSuppliers();
        if (existing.length === 0) {
            const batch = suppliers.map(s => this.addSupplier(s));
            await Promise.all(batch);
            console.log("Initial Suppliers Seeded.");
        }
    }
}

export const procurementService = new ProcurementServiceFirebase();
